In [1]:
import numpy as np
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
import itertools

Using TensorFlow backend.


ModuleNotFoundError: No module named 'matplotlib'

In [2]:
from openpyxl import load_workbook

wb=load_workbook(filename='airdata.xlsx')
sheet1=wb['airdata']

data_sheet1=[]
data_sheet2=[]

for r in sheet1.iter_rows(min_row=2,max_col=9):
   
    for cell in r:
        if cell.value != None:
            data_sheet1.append(float(cell.value))
        else:
            data_sheet1.append(float(5))
        
    
for r in sheet1.iter_rows(min_row=2,min_col=10,max_col=12):
    
    for cell in r:
        if cell.value != None:
            data_sheet2.append(float(cell.value))
        else:
            data_sheet2.append(float(5))

In [3]:
data_sheet1=np.array(data_sheet1)
data_sheet1=data_sheet1.reshape(668,9)

data_sheet2=np.array(data_sheet2)
data_sheet2=data_sheet2.reshape(668,3)

In [4]:
data_sheet1

array([[6.00000e+00, 9.20000e+01, 1.01906e+05, ..., 6.00000e+00,
        8.90000e+01, 1.01877e+05],
       [6.00000e+00, 9.20000e+01, 1.01869e+05, ..., 6.00000e+00,
        8.90000e+01, 1.01842e+05],
       [5.00000e+00, 9.40000e+01, 1.01837e+05, ..., 5.00000e+00,
        9.10000e+01, 1.01812e+05],
       ...,
       [9.00000e+00, 9.20000e+01, 1.02024e+05, ..., 1.00000e+01,
        8.80000e+01, 1.02009e+05],
       [9.00000e+00, 9.60000e+01, 1.02002e+05, ..., 5.00000e+00,
        9.40000e+01, 1.01991e+05],
       [8.00000e+00, 1.01000e+02, 1.01972e+05, ..., 0.00000e+00,
        9.60000e+01, 1.01968e+05]])

In [5]:
data_sheet2

array([[47., 45., 71.],
       [44., 43., 70.],
       [50., 49., 75.],
       ...,
       [37., 42., 63.],
       [38., 44., 64.],
       [35., 41., 60.]])

In [22]:
model = Sequential([
    Dense(9, input_shape=(9,),activation='relu'),
    Dense(27, activation='relu'),
    Dense(27, activation='relu'),
    Dense(54, activation='relu'),
    Dense(54, activation='relu'),
    Dense(3)
])

In [23]:
model.compile(Adam(lr=.0001), loss='mean_squared_error', metrics=['accuracy'])

In [24]:
model.fit(data_sheet1,data_sheet2, batch_size=2, epochs=40, shuffle=True, verbose=1)

Epoch 1/40
668/668 [==============================] - 2s 2ms/step - loss: 51385.3689 - acc: 0.8234
Epoch 2/40
668/668 [==============================] - 1s 1ms/step - loss: 289.4497 - acc: 0.9686
Epoch 3/40
668/668 [==============================] - 1s 1ms/step - loss: 288.2089 - acc: 0.9656
Epoch 4/40
668/668 [==============================] - 1s 1ms/step - loss: 301.8399 - acc: 0.9117
Epoch 5/40
668/668 [==============================] - 1s 1ms/step - loss: 300.8056 - acc: 0.9431
Epoch 6/40
668/668 [==============================] - 1s 1ms/step - loss: 328.3771 - acc: 0.8653
Epoch 7/40
668/668 [==============================] - 1s 983us/step - loss: 321.2834 - acc: 0.8862
Epoch 8/40
668/668 [==============================] - 1s 1ms/step - loss: 340.6960 - acc: 0.8787
Epoch 9/40
668/668 [==============================] - 1s 1ms/step - loss: 314.3034 - acc: 0.9311
Epoch 10/40
668/668 [==============================] - 1s 1ms/step - loss: 325.6949 - acc: 0.8787
Epoch 11/40
668/668 [====

In [26]:
model.predict(x=data_sheet1[0:10])

array([[26.825405, 21.261198, 42.31474 ],
       [26.771755, 21.309599, 42.38943 ],
       [27.037685, 21.03845 , 42.00428 ],
       [27.264187, 20.86865 , 41.729847],
       [27.30502 , 20.775267, 41.62346 ],
       [27.361172, 20.683012, 41.55091 ],
       [27.25021 , 20.694304, 41.584084],
       [27.522488, 20.373991, 41.115417],
       [27.903744, 19.916044, 40.344406],
       [28.477009, 19.40637 , 39.505295]], dtype=float32)

In [27]:
data_sheet2[0:10]

array([[47., 45., 71.],
       [44., 43., 70.],
       [50., 49., 75.],
       [53., 52., 78.],
       [45., 44., 71.],
       [46., 45., 70.],
       [36., 34., 58.],
       [28., 26., 46.],
       [21., 18., 32.],
       [15., 13., 21.]])