In [3]:
import numpy as np
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from sklearn.metrics import confusion_matrix
import itertools

In [7]:
from openpyxl import load_workbook

wb=load_workbook(filename='airdata.xlsx')
sheet1=wb['airdata']

data_sheet1=[]
data_sheet2=[]

for r in sheet1.iter_rows(min_row=2,max_col=9):
    
    for cell in r:
        if cell.value != None:
            data_sheet1.append(float(cell.value))
        else:
            data_sheet1.append(float(5))
            
            
for r in sheet1.iter_rows(min_row=2,min_col=10,max_col=12):
    
    for cell in r:
        if cell.value != None:
            data_sheet2.append(float(cell.value))
        else:
            data_sheet2.append(float(5))

In [10]:
len(data_sheet1)/9

720.0

In [11]:
data_sheet1=np.array(data_sheet1)
data_sheet1=data_sheet1.reshape(720,9)

data_sheet2=np.array(data_sheet2)
data_sheet2=data_sheet2.reshape(720,3)

In [12]:
data_sheet1

array([[6.00000e+00, 9.20000e+01, 1.01906e+05, ..., 6.00000e+00,
        8.90000e+01, 1.01877e+05],
       [6.00000e+00, 9.20000e+01, 1.01869e+05, ..., 6.00000e+00,
        8.90000e+01, 1.01842e+05],
       [5.00000e+00, 9.40000e+01, 1.01837e+05, ..., 5.00000e+00,
        9.10000e+01, 1.01812e+05],
       ...,
       [9.00000e+00, 9.20000e+01, 1.02024e+05, ..., 1.00000e+01,
        8.80000e+01, 1.02009e+05],
       [9.00000e+00, 9.60000e+01, 1.02002e+05, ..., 5.00000e+00,
        9.40000e+01, 1.01991e+05],
       [8.00000e+00, 1.01000e+02, 1.01972e+05, ..., 0.00000e+00,
        9.60000e+01, 1.01968e+05]])

In [13]:
data_sheet2

array([[47., 45., 71.],
       [44., 43., 70.],
       [50., 49., 75.],
       ...,
       [37., 42., 63.],
       [38., 44., 64.],
       [35., 41., 60.]])

In [20]:
model = Sequential([
    Dense(6 , input_shape=(9,),activation='relu'),
    Dense(12, activation='relu'),
    Dense(12, activation='relu'),
    Dense(24, activation='relu'),
    Dense(24, activation='relu'),
    Dense(3)
])

In [21]:
model.compile(Adam(lr=.0001), loss='mean_squared_error', metrics=['accuracy'])

In [22]:
model.fit(data_sheet1,data_sheet2, batch_size=2, epochs=40, shuffle=True, verbose=1)

Epoch 1/40
720/720 [==============================] - 1s 1ms/step - loss: 66595.4273 - acc: 0.5972
Epoch 2/40
720/720 [==============================] - 0s 525us/step - loss: 267.8286 - acc: 1.0000
Epoch 3/40
720/720 [==============================] - 0s 495us/step - loss: 267.6299 - acc: 1.0000
Epoch 4/40
720/720 [==============================] - 0s 495us/step - loss: 269.6468 - acc: 1.0000
Epoch 5/40
720/720 [==============================] - 0s 512us/step - loss: 269.4498 - acc: 1.0000
Epoch 6/40
720/720 [==============================] - 0s 505us/step - loss: 270.8179 - acc: 1.0000
Epoch 7/40
720/720 [==============================] - 0s 502us/step - loss: 269.7409 - acc: 1.0000
Epoch 8/40
720/720 [==============================] - 0s 494us/step - loss: 274.6836 - acc: 1.0000
Epoch 9/40
720/720 [==============================] - 0s 491us/step - loss: 269.9750 - acc: 1.0000
Epoch 10/40
720/720 [==============================] - 0s 514us/step - loss: 273.2426 - acc: 1.0000 0s - loss

In [23]:
model.predict(x=data_sheet1[0:10])

array([[22.398706, 19.024021, 33.82525 ],
       [22.39358 , 19.019993, 33.81765 ],
       [22.377893, 19.006565, 33.794044],
       [22.375696, 19.004673, 33.790703],
       [22.366663, 18.997227, 33.777275],
       [22.363855, 18.99509 , 33.773018],
       [22.382227, 19.010227, 33.800453],
       [22.381617, 19.009678, 33.799553],
       [22.369715, 18.9995  , 33.781532],
       [22.362375, 18.993275, 33.770424]], dtype=float32)

In [24]:
data_sheet2[0:10]

array([[47., 45., 71.],
       [44., 43., 70.],
       [50., 49., 75.],
       [53., 52., 78.],
       [45., 44., 71.],
       [46., 45., 70.],
       [36., 34., 58.],
       [28., 26., 46.],
       [21., 18., 32.],
       [15., 13., 21.]])