In [5]:
import numpy as np
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from sklearn.metrics import confusion_matrix
import itertools


In [8]:
from openpyxl import load_workbook

wb=load_workbook(filename='airdata.xlsx')
sheet1=wb['airdata']

data_sheet1=[]
data_sheet2=[]

for r in sheet1.iter_rows(min_row=2,max_col=9):
   
    for cell in r:
        if cell.value != None:
            data_sheet1.append(float(cell.value))
        else:
            data_sheet1.append(float(5))
        
    
for r in sheet1.iter_rows(min_row=2,min_col=10,max_col=12):
    
    for cell in r:
        if cell.value != None:
            data_sheet2.append(float(cell.value))
        else:
            data_sheet2.append(float(5))

In [11]:
data_sheet1=np.array(data_sheet1)
data_sheet1=data_sheet1.reshape(720,9)

data_sheet2=np.array(data_sheet2)
data_sheet2=data_sheet2.reshape(720,3)

In [12]:
data_sheet1

array([[6.00000e+00, 9.20000e+01, 1.01906e+05, ..., 6.00000e+00,
        8.90000e+01, 1.01877e+05],
       [6.00000e+00, 9.20000e+01, 1.01869e+05, ..., 6.00000e+00,
        8.90000e+01, 1.01842e+05],
       [5.00000e+00, 9.40000e+01, 1.01837e+05, ..., 5.00000e+00,
        9.10000e+01, 1.01812e+05],
       ...,
       [9.00000e+00, 9.20000e+01, 1.02024e+05, ..., 1.00000e+01,
        8.80000e+01, 1.02009e+05],
       [9.00000e+00, 9.60000e+01, 1.02002e+05, ..., 5.00000e+00,
        9.40000e+01, 1.01991e+05],
       [8.00000e+00, 1.01000e+02, 1.01972e+05, ..., 0.00000e+00,
        9.60000e+01, 1.01968e+05]])

In [13]:
data_sheet2

array([[47., 45., 71.],
       [44., 43., 70.],
       [50., 49., 75.],
       ...,
       [37., 42., 63.],
       [38., 44., 64.],
       [35., 41., 60.]])

In [20]:
model = Sequential([
    Dense(9 , input_shape=(9,),activation='relu'),
    Dense(54, activation='relu'),
    Dense(54, activation='relu'),
    Dense(54, activation='relu'),
    Dense(54, activation='relu'),
    Dense(3)
])

In [21]:
model.compile(Adam(lr=.0001), loss='mean_squared_error', metrics=['accuracy'])

In [23]:
model.fit(data_sheet1,data_sheet2, batch_size=2, epochs=60, shuffle=True, verbose=1)

Epoch 1/60
720/720 [==============================] - 0s 565us/step - loss: 636.1062 - acc: 0.6111
Epoch 2/60
720/720 [==============================] - 0s 525us/step - loss: 506.1411 - acc: 0.6833
Epoch 3/60
720/720 [==============================] - 0s 534us/step - loss: 519.9244 - acc: 0.6500
Epoch 4/60
720/720 [==============================] - 0s 556us/step - loss: 513.7964 - acc: 0.7056
Epoch 5/60
720/720 [==============================] - 0s 583us/step - loss: 460.9081 - acc: 0.7306
Epoch 6/60
720/720 [==============================] - 0s 532us/step - loss: 429.8936 - acc: 0.7861
Epoch 7/60
720/720 [==============================] - 0s 589us/step - loss: 430.8488 - acc: 0.7583
Epoch 8/60
720/720 [==============================] - 0s 493us/step - loss: 445.7479 - acc: 0.7778
Epoch 9/60
720/720 [==============================] - 0s 518us/step - loss: 410.5889 - acc: 0.8361
Epoch 10/60
720/720 [==============================] - 0s 461us/step - loss: 395.5775 - acc: 0.8139
Epoch 11/

In [24]:
model.predict(x=data_sheet1[0:20])

array([[26.57761 , 25.337715, 41.640717],
       [26.779049, 25.529787, 41.956253],
       [25.833385, 24.628077, 40.475018],
       [25.425545, 24.23918 , 39.83618 ],
       [25.039392, 23.870981, 39.231327],
       [24.66336 , 23.512415, 38.642334],
       [25.43697 , 24.250067, 39.854076],
       [25.022388, 23.854773, 39.20471 ],
       [24.133022, 23.006721, 37.81163 ],
       [22.598104, 21.543148, 35.40742 ],
       [21.788895, 20.771555, 34.139915],
       [21.884724, 20.862923, 34.29003 ],
       [22.088104, 21.056856, 34.60858 ],
       [22.182238, 21.146597, 34.75602 ],
       [21.499245, 20.49536 , 33.686234],
       [21.583397, 20.57561 , 33.818054],
       [21.723108, 20.708824, 34.03688 ],
       [22.625343, 21.569124, 35.450096],
       [23.26312 , 22.17727 , 36.449093],
       [24.099245, 22.974514, 37.758743]], dtype=float32)

In [25]:
data_sheet2[0:20]

array([[47., 45., 71.],
       [44., 43., 70.],
       [50., 49., 75.],
       [53., 52., 78.],
       [45., 44., 71.],
       [46., 45., 70.],
       [36., 34., 58.],
       [28., 26., 46.],
       [21., 18., 32.],
       [15., 13., 21.],
       [13., 11., 18.],
       [13., 11., 18.],
       [12., 11., 17.],
       [12., 10., 16.],
       [12., 10., 16.],
       [11.,  9., 15.],
       [11.,  9., 15.],
       [17., 15., 25.],
       [43., 42., 65.],
       [45., 45., 68.]])