In [15]:
import numpy as np
import keras
from keras import backend as K
from keras.models import Sequential
from keras.layers import Activation
from keras.layers.core import Dense, Flatten
from keras.optimizers import Adam
from keras.metrics import categorical_crossentropy
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from keras.layers.convolutional import *
from matplotlib import pyplot as plt
from sklearn.metrics import confusion_matrix
import itertools
import matplotlib.pyplot as plt

%matplotlib inline

In [35]:
from openpyxl import load_workbook

wb=load_workbook(filename='2week/airdata.xlsx')
sheet1=wb['airdata']

data_sheet=[]
data_sheet2=[]

for r in sheet1.iter_rows(min_row=1,max_col=9):
   
    for cell in r:
        if cell.value != None:
            data_sheet.append(float(cell.value))
        else:
            data_sheet.append(float(5))
        
    
for r in sheet1.iter_rows(min_row=1,min_col=10,max_col=12):
    
    for cell in r:
        if cell.value != None:
            data_sheet2.append(float(cell.value))
        else:
            data_sheet2.append(float(5))
        
    




In [38]:
len(data_sheet)/9

720.0

In [39]:
data_sheet=np.array(data_sheet)
data_sheet=data_sheet.reshape(720,9)

data_sheet2=np.array(data_sheet2)
data_sheet2=data_sheet2.reshape(720,3)


In [40]:
data_sheet

array([[6.00000e+00, 9.20000e+01, 1.01906e+05, ..., 6.00000e+00,
        8.90000e+01, 1.01877e+05],
       [6.00000e+00, 9.20000e+01, 1.01869e+05, ..., 6.00000e+00,
        8.90000e+01, 1.01842e+05],
       [5.00000e+00, 9.40000e+01, 1.01837e+05, ..., 5.00000e+00,
        9.10000e+01, 1.01812e+05],
       ...,
       [9.00000e+00, 9.20000e+01, 1.02024e+05, ..., 1.00000e+01,
        8.80000e+01, 1.02009e+05],
       [9.00000e+00, 9.60000e+01, 1.02002e+05, ..., 5.00000e+00,
        9.40000e+01, 1.01991e+05],
       [8.00000e+00, 1.01000e+02, 1.01972e+05, ..., 0.00000e+00,
        9.60000e+01, 1.01968e+05]])

In [41]:
data_sheet2

array([[47., 45., 71.],
       [44., 43., 70.],
       [50., 49., 75.],
       ...,
       [37., 42., 63.],
       [38., 44., 64.],
       [35., 41., 60.]])

In [42]:
model = Sequential([
    Dense(18 , input_shape=(9,),activation='relu'),
    Dense(54, activation='relu'),
    Dense(54, activation='relu'),
    Dense(54, activation='relu'),
    Dense(54, activation='relu'),
    Dense(3)
])

In [43]:
model.compile(Adam(lr=.0001), loss='mean_squared_error', metrics=['accuracy'])

In [54]:
model.fit(data_sheet,data_sheet2, batch_size=2, epochs=40, shuffle=True, verbose=1)

Epoch 1/40
720/720 [==============================] - 1s 848us/step - loss: 299.0064 - acc: 0.9056
Epoch 2/40
720/720 [==============================] - 1s 837us/step - loss: 294.3040 - acc: 0.8722
Epoch 3/40
720/720 [==============================] - 1s 804us/step - loss: 297.9601 - acc: 0.9250
Epoch 4/40
720/720 [==============================] - 1s 826us/step - loss: 291.1186 - acc: 0.8903
Epoch 5/40
720/720 [==============================] - 1s 845us/step - loss: 296.3645 - acc: 0.8542
Epoch 6/40
720/720 [==============================] - 1s 829us/step - loss: 322.7855 - acc: 0.8181
Epoch 7/40
720/720 [==============================] - 1s 934us/step - loss: 308.6827 - acc: 0.8319
Epoch 8/40
720/720 [==============================] - 1s 861us/step - loss: 301.2790 - acc: 0.8528
Epoch 9/40
720/720 [==============================] - 1s 851us/step - loss: 311.6351 - acc: 0.8319
Epoch 10/40
720/720 [==============================] - 1s 881us/step - loss: 298.9790 - acc: 0.8694
Epoch 11/

In [57]:
model.predict(x=data_sheet[0:10])

array([[38.64042 , 38.313755, 39.3093  ],
       [39.2177  , 38.951397, 39.76486 ],
       [36.685467, 36.155334, 37.719696],
       [35.322952, 34.513374, 36.566837],
       [34.397495, 33.591595, 35.862053],
       [33.68986 , 32.853645, 35.309925],
       [34.580345, 33.28796 , 35.877316],
       [32.573063, 30.65528 , 34.147938],
       [28.943544, 26.0795  , 31.084183],
       [24.404829, 20.83206 , 27.388924]], dtype=float32)

In [58]:
data_sheet2[0:10]

array([[47., 45., 71.],
       [44., 43., 70.],
       [50., 49., 75.],
       [53., 52., 78.],
       [45., 44., 71.],
       [46., 45., 70.],
       [36., 34., 58.],
       [28., 26., 46.],
       [21., 18., 32.],
       [15., 13., 21.]])